
name: Deploy CareerBuddy App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          VITE_APP_VERSION: ${{ github.sha }}
          VITE_APP_NAME: "CareerBuddy"
          VITE_ENABLE_ANALYTICS: "false"
          VITE_BUILD_TIME: ${{ github.event.repository.updated_at }}
          VITE_BUILD_COMMIT: ${{ github.sha }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy_production:
    needs: build_and_test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      
      # Here you would typically add deployment steps
      # For example, deploying to Vercel, Netlify, or any other provider
      # This is a placeholder for actual deployment instructions
      
      - name: Deploy to production
        run: echo "Deploying to production..."
        # Example for Netlify deployment:
        # uses: netlify/actions/cli@master
        # with:
        #   args: deploy --dir=dist --prod
        #   secrets: '{"NETLIFY_AUTH_TOKEN":"${{ secrets.NETLIFY_AUTH_TOKEN }}","NETLIFY_SITE_ID":"${{ secrets.NETLIFY_SITE_ID }}"}'
